cleanup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,50 +1,68 @@
-#!/bin/bash
+#!/bin/sh
 custom_readlink() { [ ! -h "$1" ] && echo "$1" || (local link="$(expr "$(command ls -ld -- "$1")" : '.*-> \(.*\)$')"; cd $(dirname $1); custom_readlink "$link" | sed "s|^\([^/].*\)\$|$(dirname $1)/\1|"); }
-npm_path=`dirname "$(custom_readlink ${BASH_SOURCE[0]})"`
+NPM_PATH=$( dirname $(custom_readlink $0) )
 
-user=$(who am i 2> /dev/null)
-if [ -z "$user" ]; then
-	user=$(whoami)
+# find user
+user=$(whoami | sed 's/.*[\/\\]//')
+if [ $user = "root" ]; then
+  user=$( who am i 2> /dev/null | awk '{print $1}')
+fi
+USER_HOME=$(eval echo ~$user)
+
+# check for source files
+if [ -e $USER_HOME/.bashrc ]; then
+  BASH_SOURCE_FILE="$USER_HOME/.bashrc"
+elif [ -e $USER_HOME/.bash_profile ]; then
+  BASH_SOURCE_FILE="$USER_HOME/.bash_profile"
 fi
 
-user=$( echo "$user" | awk '{print $1}')
-if [ -e /home/$user/.bashrc ]; then
-	source_file="/home/$user/.bashrc"
-elif [ -e /Users/$user/.bash_profile ]; then
-	source_file="/Users/$user/.bash_profile"
-else
-	user2=$(echo $user | sed 's/.*[\/\\]//')
-	if [ -e /c/Users/$user/.bashrc ]; then
-		source_file="/c/Users/$user/.bashrc"
-	elif [ -e /c/Users/$user2/.bashrc ]; then
-		user=$user2
-		source_file="/c/Users/$user/.bashrc"
-	fi
+if [ -e $USER_HOME/.zshrc ]; then
+  ZSH_SOURCE_FILE="$USER_HOME/.zshrc"
 fi
 
-if [ ! -z $source_file ]; then
-	bash_comment="# added for npm-completion https://github.com/Jephuff/npm-bash-completion"
-	bash_variable="PATH_TO_NPM_COMPLETION=\"$npm_path\""
-	npm_source="source \$PATH_TO_NPM_COMPLETION/npm-completion.sh"
+# add entries to source files
+COMMENT="# added for npm-completion https://github.com/Jephuff/npm-bash-completion"
+VARIABLE="PATH_TO_NPM_COMPLETION=\"$NPM_PATH\""
+NPM_SOURCE="source \$PATH_TO_NPM_COMPLETION/npm-completion.sh"
+if [ ! -z $BASH_SOURCE_FILE ]; then
+  grep -F "$COMMENT" $BASH_SOURCE_FILE > /dev/null
+  if [ $? != 0 ]; then
+    printf "\n$COMMENT" >> $BASH_SOURCE_FILE
+  fi
 
-	grep -F "$bash_comment" $source_file > /dev/null
-	if [ $? != 0 ]; then
-		printf "\n$bash_comment" >> $source_file
-	fi
+  grep -F "$VARIABLE" $BASH_SOURCE_FILE > /dev/null
+  if [ $? != 0 ]; then
+    printf "\n$VARIABLE" >> $BASH_SOURCE_FILE
+  fi
 
-	grep -F "$bash_variable" $source_file > /dev/null
-	if [ $? != 0 ]; then
-		printf "\n$bash_variable" >> $source_file
-	fi
+  grep -F "$NPM_SOURCE" $BASH_SOURCE_FILE > /dev/null
+  if [ $? != 0 ]; then
+    printf "\n$NPM_SOURCE" >> $BASH_SOURCE_FILE
+  fi
+fi
 
-	grep -F "$npm_source" $source_file > /dev/null
-	if [ $? != 0 ]; then
-		printf "\n$npm_source" >> $source_file
-	fi
+if [ ! -z $ZSH_SOURCE_FILE ]; then
+  grep -F "$COMMENT" $ZSH_SOURCE_FILE > /dev/null
+  if [ $? != 0 ]; then
+    printf "\n$COMMENT" >> $ZSH_SOURCE_FILE
+  fi
 
-	echo -e "\nadd this line to a cron job or startup script"
-	echo "    PATH=\$PATH:$(dirname $(which node)):$(dirname $(which npm)) && cd $npm_path && ./update"
-	echo -e "\nrestart terminal to start using\n"
+  grep -F "$VARIABLE" $ZSH_SOURCE_FILE > /dev/null
+  if [ $? != 0 ]; then
+    printf "\n$VARIABLE" >> $ZSH_SOURCE_FILE
+  fi
+
+  grep -F "$NPM_SOURCE" $ZSH_SOURCE_FILE > /dev/null
+  if [ $? != 0 ]; then
+    printf "\n$NPM_SOURCE" >> $ZSH_SOURCE_FILE
+  fi
+fi
+
+# echo messages
+if [ ! -z $ZSH_SOURCE_FILE -o ! -z $BASH_SOURCE_FILE ]; then
+  echo "\nadd this line to a cron job or startup script"
+  echo "    PATH=\$PATH:$(dirname $(which node)):$(dirname $(which npm)) && cd $NPM_PATH && ./update"
+  echo "\nrestart terminal to start using\n"
 else
-	echo -e "\ncouldn't find ~/.bashrc or ~/.bash_profile. Please create one of these file and run\n    npm-completion-setup\n"
+  echo "\ncouldn't find source file. Please create ~/.bashrc, ~/.bash_profile or ~/.zshrc and run\n    npm-completion-setup\n"
 fi
